name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker backend image
      run: docker build --file ./back_end/Dockerfile --tag todo-backend:$(date +%s);

    - name: Build the Docker frontend image
      run: docker build --file ./front_end/Dockerfile --tag todo-frontend:$(date +%s);
